import Head from 'next/head'
import ControlCameraIcon from '@mui/icons-material/ControlCamera';
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>sistema de alerta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ControlCameraIcon/>
      <h1 className="text-3xl font-bold underline text-blue-300 ">
      Texto em Tailwind icon Materil UI.
      </h1>
    </div>
  )
}
